### ISSUE TITLE
AStarFinder in Unity (not contains System.Threading.Tasks;)

### ISSUE THREAD

**Issue by cathy33** [juhgiyo/EpPathFinding.cs#10]
AStarFinder line78 (Parallel.ForEach(neighbors, neighbor =>)

Parallel is not exist

**Comment by juhgiyo** [comment]
Just made a quick fix on new commit cf07dea1acefd6b2737e7e53f5ebea6c470902b2 for Unity.

Planning to add directives for Unity later! :)

**Comment by cathy33** [comment]
get it
