### ISSUE TITLE
Returning Failed Path

### ISSUE THREAD

**Issue by jamstone** [juhgiyo/EpPathFinding.cs#11]
Hey I found that the AStarFinder was returning paths the lead to... nowhere in particular. I'm assuming what happened was the finder found no suitable paths, and simply returned the path back from the most recently searched node.

My solution to this problem was to change this:

`if (openList.Count == 0) return Node.Backtrace(node);`

...to...

`if (openList.Count == 0 && node == endNode) return Node.Backtrace(node);`

Not sure if that fits what you were aiming for, but it makes it infinitely more useful to me.

**Comment by juhgiyo** [comment]
I think you can just remove that line and will work just fine as you are aiming for.
AStarFinder was from other contributor, and it seems like it was added to debug the failed path finding.
I am on the trip right now, so I can't test and update the code.
I will update the code when I get back from the trip after few tests! :)

**Comment by juhgiyo** [comment]
Fixed to return empty list when the route is not found instead of returning the path to the last accessed node. (c4c5f319d0b62add93c758b81de85e8199f6beb4)
