### ISSUE TITLE
A horizontal path with a hole in the middle is not blocked

### ISSUE THREAD

**Issue by tzachshabtay** [juhgiyo/EpPathFinding.cs#3]
Hi, I believe I found a bug.
The scenario is simple: a horizontal walking path with a hole in the middle ([0,0],[1.0].[2.0].[4.0] when trying to get from [0,0] to [4,0]).
I expect the algorithm to reach [2,0] and then get stuck, but that's not what happens.
It gets to [2,0], and then in JumpPointFinder.jumpLoop under line 524, since dy is 0 the second condition passes (it checks the current position) and then it junps to [3,0] even though it's not walkable.
I haven't checked but I'm guessing a vertical line would have the same issue (only with the first condition and not the second).

Here's an Nunit test that reproduces the issue:

        [TestCase(5,5, 0,0, 4,0,    0,0, 1,0, 2,0, 4,0, Result = false)]
		public bool FailedPathTest(int width, int height, int fromX, int fromY, int toX, int toY, params int[] walkablePoints)
		{
			bool[][] matrix = getGrid(width, height, walkablePoints);

			StaticGrid grid = new StaticGrid (width, height, matrix);
			JumpPointParam input = new JumpPointParam (grid, new GridPos(fromX, fromY), new GridPos(toX, toY), false, true, false);
			var cells = JumpPointFinder.FindPath (input);
			return cells.Count > 0;
		}

		private bool[][] getGrid(int width, int height, params int[] walkablePoints)
		{
			bool[][] array = new bool[width][];

			for (int x = 0; x < width; x++)
			{
				array[x] = new bool[height];
			}

			for (int pointIndex = 0; pointIndex < walkablePoints.Length; pointIndex += 2)
			{
				int x = walkablePoints[pointIndex];
				int y = walkablePoints[pointIndex + 1];
				array[x][y] = true;
			}
			return array;
		}

**Comment by juhgiyo** [comment]
Hello, 
I think there should be some clarification.

Are you saying you are getting a path with your condition?
When I tried with your case, I am not getting any path. (which it shouldn't)

I am wondering you might not have used the latest version if you are getting a path with your condition, or I am misunderstanding your question from the start.

Please let me know then!
Thanks!

**Comment by juhgiyo** [comment]
If you are reporting the bug of that jumpLoop function jumps to cell(3,0) at line 524, when cell(3,0) is not walkable. You should think that line as the algorithm tries to jump to cell(3,0) (Not actually jumped), and it actually returns "null" by checking whether current cell is walkable or not at line 452

**Comment by tzachshabtay** [comment]
Hmm, I thought I had the latest version but apparently that wasn't the case. Downloaded it now and it's fixed (an older version did return a path with this test).
Thanks.
