### ISSUE TITLE
Split library from demo and publish nuget package

### ISSUE THREAD

**Issue by htoothrot** [juhgiyo/EpPathFinding.cs#6]
It would be really great if you could:

1) Separate the path finding code from the demo so the project for the library can easily be included in other solutions as a library.
2) Publish a nuget package.

Thanks for the project!

**Comment by juhgiyo** [comment]
Thank you for the advice!

Yea, I am planning to work on that pretty soon!

**Comment by juhgiyo** [comment]
Done!

[Nuget Package](https://www.nuget.org/packages/EpPathFinding.cs/)

**Comment by htoothrot** [comment]
That was quite fast. Many thanks!

I really do appreciate it.
