### ISSUE TITLE
JumpPointFinder.GetFullPath(...) is broken.

### ISSUE THREAD

**Issue by omegachysis** [juhgiyo/EpPathFinding.cs#9]
Instead of returning a full path, as of the latest version from Nuget `JumpPointFinder.GetFullPath(...)` only returns the jump points.  This was tested thoroughly in my project, and copying the code from the following older commit directly into my project fixed the problem: 
 a40f199b0e444fe98907d5e33c997aeb687942a7

Direct link to the problem function here:
https://github.com/juhgiyo/EpPathFinding.cs/blob/master/EpPathFinding.cs/EpPathFinding.cs/PathFinder/JumpPointFinder.cs#L157

**Comment by juhgiyo** [comment]
Thank you for bringing up the issue, and sorry for the inconvenience.
c30c583dce00c53e63be982a4f252712eeeff548 will fix your problem.
If you update the nuget package the bug would have fixed! 👍

**Comment by omegachysis** [comment]
This library, and you, are great.  Thank you for the quick fix.
